---
- name: Configure AWX
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - secrets.yml
    - vars.yml

  environment:
    K8S_AUTH_KUBECONFIG: "{{ awxsetup.kubeconfig }}"
    CONTROLLER_USERNAME: admin
    CONTROLLER_HOST: "http://{{ awxsetup.name }}.{{ awxsetup.baseurl }}" # <- Change to https if TLS configured
    CONTROLLER_VERIFY_SSL: false 

  tasks:
  - name: Roll out AWX on Kubernetes
    include_tasks: 01_awx_kube.yml

  - name: Configure AWX
    include_tasks: 02_awx_config.yml

  - name: delete Demo 
    include_tasks: 03_awx_delete_default.yml
    # Optional: Will clean up Standard Demo Credentials, Org and template

  - name: AWX-Password
    debug: 
      msg: "Password: {{ awxadmin.resources[0].data.password | b64decode }}"
